### ISSUE TITLE
Google Gets Suspicious

### ISSUE THREAD

**Issue by meyersbs** [slifty/internet_noise#21] opened 2017-03-31 14:55 UTC
Running the algorithm for an extended period of time (about a day and a half now) results in Google getting suspicious:

![image](https://cloud.githubusercontent.com/assets/4073851/24555812/68ba70d6-1600-11e7-8b12-31ed176b07d2.png)

**Comment by gmittal** [comment] 2017-03-31 17:08
Reference: #4

**Comment by slifty** [comment] 2017-04-05 03:25
Closing this as a duplicate, but the issue is noted

**Closed as completed by slifty** 2017-04-05 03:25 UTC
Labels: duplicate
